# Generated by Django 3.1 on 2020-08-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='user',
        ),
    ]
